package candyBar.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class Candybar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CANDYBAR.ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CANDYBAR.NAME
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    private String name;

    private List<Ingredient> ingredients = new ArrayList<>();
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CANDYBAR.ID
     *
     * @return the value of PUBLIC.CANDYBAR.ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CANDYBAR.ID
     *
     * @param id the value for PUBLIC.CANDYBAR.ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CANDYBAR.NAME
     *
     * @return the value of PUBLIC.CANDYBAR.NAME
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CANDYBAR.NAME
     *
     * @param name the value for PUBLIC.CANDYBAR.NAME
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    public List<Ingredient> getIngredients() {
        return ingredients;
    }
}