package candyBar.mybatis.model;

public class SourceContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOURCE_CONTRACT.ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOURCE_CONTRACT.COUNTRY_OF_ORIGIN
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    private String countryOfOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOURCE_CONTRACT.NAME
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOURCE_CONTRACT.PRICE
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOURCE_CONTRACT.INGREDIENT_ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    private Integer ingredientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOURCE_CONTRACT.ID
     *
     * @return the value of PUBLIC.SOURCE_CONTRACT.ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOURCE_CONTRACT.ID
     *
     * @param id the value for PUBLIC.SOURCE_CONTRACT.ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOURCE_CONTRACT.COUNTRY_OF_ORIGIN
     *
     * @return the value of PUBLIC.SOURCE_CONTRACT.COUNTRY_OF_ORIGIN
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOURCE_CONTRACT.COUNTRY_OF_ORIGIN
     *
     * @param countryOfOrigin the value for PUBLIC.SOURCE_CONTRACT.COUNTRY_OF_ORIGIN
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public void setCountryOfOrigin(String countryOfOrigin) {
        this.countryOfOrigin = countryOfOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOURCE_CONTRACT.NAME
     *
     * @return the value of PUBLIC.SOURCE_CONTRACT.NAME
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOURCE_CONTRACT.NAME
     *
     * @param name the value for PUBLIC.SOURCE_CONTRACT.NAME
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOURCE_CONTRACT.PRICE
     *
     * @return the value of PUBLIC.SOURCE_CONTRACT.PRICE
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOURCE_CONTRACT.PRICE
     *
     * @param price the value for PUBLIC.SOURCE_CONTRACT.PRICE
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOURCE_CONTRACT.INGREDIENT_ID
     *
     * @return the value of PUBLIC.SOURCE_CONTRACT.INGREDIENT_ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public Integer getIngredientId() {
        return ingredientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOURCE_CONTRACT.INGREDIENT_ID
     *
     * @param ingredientId the value for PUBLIC.SOURCE_CONTRACT.INGREDIENT_ID
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    public void setIngredientId(Integer ingredientId) {
        this.ingredientId = ingredientId;
    }
}