package candyBar.mybatis.dao;

import candyBar.mybatis.model.Candybar;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CandybarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDYBAR
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDYBAR
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int insert(Candybar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDYBAR
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    Candybar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDYBAR
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    List<Candybar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CANDYBAR
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int updateByPrimaryKey(Candybar record);
}