package candyBar.mybatis.dao;

import candyBar.mybatis.model.Ingredient;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface IngredientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INGREDIENT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INGREDIENT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int insert(Ingredient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INGREDIENT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    Ingredient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INGREDIENT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    List<Ingredient> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INGREDIENT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int updateByPrimaryKey(Ingredient record);
}